version: '3.8'

services:
  back:
    image: inksne/crypt-back-image:latest
    container_name: back-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "10000"]